---
language: python
python:
  - '3.7'
  - '3.8'
env:
  global:
    - secure: ZCgbV4LuqpVvc1MwHXq6P8O52l4uQRCnU7rMGNtchEj2fmFbi6eisE+nAZxS6YNMlyMCXQkgM5Snxu9VGAxEcGFGHUY7MfnwSisGR8s+CNFtUyUBExfIgguDrp2VODgcGBhg02qSEY4B2JjoJbCvZ8eo8ICZ2FOSAafyTWlfpAYssU+Oy5G6R/NPeVHra++SOXP2aGaaYJUniFOrIbCocLEgzLcDcipNrlo6jiO7h0pgwH/PCd9PUJMKivT68GHsg1O6NH4AzDaRtO+qB5njENijuJNZ1IvbM7beV6MxKJQ7yczyVwyhJCApKt5sQNVS4pinFsclea5nnfJvCcUdSq2B+eYfPx9mXrMnMFw2uAZ/PCBhdelofwpnz2MJeSypLGg1oaJn2FHBYS2X3dOrskDNmcaSe55IaZ5D9Xa+Pm8Gv6ev4gsZ+9dIfVRW/DZSa3sPCeyDa8ENaZrr12gVtQurYprfFkF1Zl0PSn4d3ZVVs8pnuNm0hgEie/xdYFo5WdNIb4RQFA61pFMFbeKZadTfBSKqLJ0pWZTJeBkF59TSBBhYbIUca8nQ7oHJFtxj3i/f/kSsXZE5gj/BE+5CwE0+1e3t8fsFNIssQIu4xG9Vm2pQOHY9+99swFW5iPR5y84kgUNDSut8ZGOCtx91hFJx7R/sZdVZjKCgvkUiSSM=
    - secure: YxLMe4uratDfrKQk/4QdmIOugn9/yl3Zs32TJkXwHv5O+dcswCKex9p2JU4x3c1o79sAbImbLU+NnxJb40bl90mJ7bHEjEXtf1Ota44jaPNMqo2JpGIZlQ5hcbj3ROFEMU5YVeCzuw4iRX3VmqHwP7S2Zov7L/DMnM8mK9GF5DC7qF532DOSIiQPR0x2KO4IpHYVgPFVl1ixVL7tFbp5PdGBmIIYan2l8bFUb6CrBZtkpOKLzYAV5xZsR+YUFZHKyO9yb1QrRd9GcmKHlF4neTR42Qu+nXxhlQXqdPSckWikJgNt1Y2ztwq5l7+ZhjGls7MDbKv/fcDbGGN1JUQwmyjwUJpblND9LTCxZYFrCA1Lt1/oHQ+NJlzCjiyCZ4sFaZGfPNX3U65Re7bLo5VrEUc/bh82BSLvE3kKDQXQvj8Kix6JZzfXu1ilXw3xiR+MC1+/Di4WGzu6cDBdDcMCFH+uJyX6Y5ZU6gE5Csw6x1Q4AbM0nJyPg9ILBlNUPosYgwFSqYMJgazdVFapLWr2Aidk+x35NAfUGHsox3QTYNJaz+Jwd1zPW/MKi015/okYM7tiBOSc7aEOQcpdwkr2kcXDm2Lk5m/RafW5xVcZKuSV4NHvyl2O1eoIxARRQKowwagAM3Q+p+z2/J/47F2QMitDm7FCW7p3UyHK3Skq8dQ=
install:
  - pip install --upgrade pip
  - pip install -r requirements-build.txt
script:
  - nb test
jobs:
  include:
    - stage: deploy
      python: 3.7
      script: nb pypi
