---
dist: xenial
sudo: true
language: python
python:
  - '2.7'
  - '3.7'
env:
  global:
    - secure: vwPkmKM6XQu1jTVA33kJ025ccQuBhK91eORRF2RpoAI5pY1AHqwkUcaunhwLntt0zP1bFiq72U42BDd6E9haHrJO1298ZxzVDfE18HhR+0f4HtOpBoVMBYGX5cq3iYad5aGLmhTmM8saxLv4OwXihCdf5n+o5jbVj32ZlreGL1MDVwSQs4zo8LuiqaTkdvBjk3woYFhEkJ5VP59WN2SIRHFyG66094v0gN3ZbeS3I0S8NAksPPSK6HRGTjLHf1a7HhCIjqAjkAX4/NMyLLURuuWdgsdoRfUpiXpsCV4QWGUFfB4i6mWU7P8mQMEYmyutawVZIOTXke2hHjYBPsYlRjMtWS8p0sIgkjxHGL/hAL1aVhCK/n48d118zPJQr3VbdbjvJ3zrdv9gc/sp79Sg0Fz8rKPNrbxtcqadLw2NHnUAJBO/mvUcoxxta2k/ZdUbx/eEv+WJR1mokPo33WWA7krMzzYUtuEwsM4JnGt8IbZLefYeSkmCscp1Xjkgwqi58RcM9wZsVZRrDqCRRkbZMXGGuS864OHo921aepmTCpie2lnmDPbGAVK+b18NbjLsk7MUKFooQoXhJ7tes/YX9iduDgjtXHI6hPpZjLI2utCwlnea0ijKLjf0qwI55gH+YaHZUim17DAjOiMegNVQJP+ywRp6gAiz+pnCU8P7SXQ=
    - secure: vCPE38POVEMWgVFRBWc7RT0RaNTYbAuzR3QNnKAmKPRKmMde5w2gUS4NH6fEiUVk5hdx9bOQv3CjU4jf6RjNNYUSQqV8l6QM5v6xJZCEixUy+kJIiAniC0emPczROIQh8JsdLxQCkevx5P6sYK1RfNLZkfvKYXBJJ637krW3p0tSSkKiUwScn4J+7/BbH2/MZGtxKOcmRf0e+canPNOa68b/WCxC176JeP8keJ6aiDVDBkaF2f45tXhca0L6y23GFU1vMy7VZITEXhHb4AztlHYzcovey8y6yBzSlg/SNo8nvfV0cCacBc+PyjQxpMno/S43/EzD7nnVf+VvCdTR+GsCO/tE3UPY5x04Pmzd1YLCZsFJu+2vXW68NLo5TYBWM0Qw0Ho15brtrmLMXegMlnN5R4kxG5fSdxA/C006MpTFZt8wyVMy4sHByqw9dr36IROV4/upakZ7ozhGiDlP4u8tGRTuUkuCu51XuZJcRlat4tzXrwX/0qR/KP2YjRQGVn7mrSN+Owhx/9Nh1XS9CqRKPkNwPHFw672dt/QkT8HLoxMAhgGSag+qJwg3EW2nkG+LmSA73ywTeUL7vB+fglcoJEGvpWQmJYF8pFPQXV3h34bivFj3JbVBKytJi8mDSWKWkShIh1LClNA/GjmkE0q8gmQkvbIRNiRyW67Ck7U=
install:
  - pip install --upgrade pip
  - pip install -r requirements-build.txt
script:
  - nb test
jobs:
  include:
    - stage: deploy
      python: 3.7
      script: nb pypi
